"""Copy the plugin's shaders and constants into the demo, by script, never by hand.

    python3 demo/tools/sync_shaders.py          rewrite the generated block of demo/plugin.js
    python3 demo/tools/sync_shaders.py --print  print the block instead

`demo/plugin.js` carries one region between the lines

    //=== BEGIN GENERATED by demo/tools/sync_shaders.py
    //=== END GENERATED

and this script owns it. Everything in it is text lifted out of the C++:

  - the five GLSL strings of `source/Shaders.cpp` (the version line, the vertex
    body and the capture, resample and output bodies), each spliced into a
    JavaScript template literal with its tabs, its comments and its blank lines
    exactly as they are. A template literal cannot hold a raw backtick, a
    backslash or a `${`, so those three are escaped (none occurs today) and
    `check_shaders.py` undoes exactly those three and refuses any other escape;
  - the print-data layout (`source/Shaders.h`), every constant of the projector
    and the print (`source/Model.h`: the film's geometry, the shutter's segment
    cap, the weave law, the scratch, dust and hair rates and sizes, the splice
    wash, the cue timing, the three fade rates), and the control counts, option
    lists, frame rates and lamp temperatures (`source/Controls.h`,
    `Controls.cpp`). Each literal is copied as the C++ spells it; an expression
    naming another constant (kMargin, kPitch) is copied with that name pointed
    at the copied constant, so JavaScript evaluates it in double as the
    compiler does; a `float` constant is wrapped in Math.fround, because the
    plugin promotes the float, not the decimal, when it computes with it.

What this script does NOT write is the port: the hash, the shutter's closed
form, the segments, the weave, the scratches, dust, hair, splices and cues, the
retention, the lamps' black bodies, every control's law and Gate::ProcessOpenGL's
clock, hold and print upload in plugin.js are a hand translation of Model.cpp,
Controls.cpp and Gate.cpp, and only a reader checks those.

Run it whenever a shader or a constant changes in the plugin, then
`python3 demo/tools/check_shaders.py` (tools/verify.sh runs it) to confirm.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PLUGIN_JS = os.path.join(REPO, "demo", "plugin.js")

BEGIN = "//=== BEGIN GENERATED by demo/tools/sync_shaders.py"
END = "//=== END GENERATED"

# JS constant, C++ symbol in source/Shaders.cpp. Order is the file's order.
SHADERS = [
    ("VERTEX_BODY", "kVertexBody"),
    ("CAPTURE_BODY", "kCaptureBody"),
    ("RESAMPLE_BODY", "kResampleBody"),
    ("OUTPUT_BODY", "kOutputBody"),
]


def read(path):
    with open(os.path.join(REPO, path)) as handle:
        return handle.read()


def cpp_shader(source, symbol):
    match = re.search(r'const char\* const ' + symbol + r' = R"\((.*?)\)";', source, re.S)
    if match is None:
        raise SystemExit(f"{symbol} not found in source/Shaders.cpp")
    return match.group(1)


def cpp_version(source):
    match = re.search(r'const char\* const kVersion = "(.*?)";', source)
    if match is None:
        raise SystemExit("kVersion not found in source/Shaders.cpp")
    return match.group(1)


def escape_template(text):
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def number(token):
    """A C++ numeric literal as JavaScript: drop a float's f suffix and a u suffix, nothing else."""
    token = token.strip()
    token = re.sub(r"(?<=[0-9.])f\b", "", token)
    token = re.sub(r"(?<=[0-9a-fA-F])u\b", "", token)
    return token


def scalars(source, types, prefix):
    """`constexpr T kName = expr;` -> (name, JavaScript expression), in file order."""
    out = []
    for match in re.finditer(r"constexpr (" + types + r") (k\w+)\s*=\s*([^;{\[]+);", source):
        kind, name, expr = match.group(1), match.group(2), match.group(3)
        expr = re.sub(r"\s+", " ", number(expr))
        expr = re.sub(r"\b(k\w+)\b", prefix + r".\1", expr)
        if kind == "float":
            expr = f"Math.fround({expr})"
        out.append((name, expr))
    return out


def names_of(controls_cpp, function):
    match = re.search(function + r"\( int index \)\s*\{\s*static const char\* const names\[ \w+ \] = \{ (.*?) \};", controls_cpp, re.S)
    if match is None:
        raise SystemExit(f"{function}'s names not found in source/Controls.cpp")
    return re.findall(r'"([^"]*)"', match.group(1))


def table_of(controls_cpp, function, array):
    match = re.search(function + r"\( int index \)\s*\{\s*static const double " + array + r"\[ \w+ \] = \{ (.*?) \};", controls_cpp, re.S)
    if match is None:
        raise SystemExit(f"{function}'s {array} not found in source/Controls.cpp")
    return [number(t) for t in match.group(1).split(",") if t.strip()]


def assignments(name, pairs):
    lines = [f"const {name} = {{}};"]
    for key, expr in pairs:
        lines.append(f"{name}.{key} = {expr};")
    return lines


def block():
    shaders_cpp = read("source/Shaders.cpp")
    shaders_h = read("source/Shaders.h")
    model_h = read("source/Model.h")
    controls_h = read("source/Controls.h")
    controls_cpp = read("source/Controls.cpp")

    out = [BEGIN + " from source/ -- do not edit by hand.", ""]
    out.append("// source/Shaders.cpp, verbatim. `assemble` (below the block) is Shaders.cpp's.")
    out.append(f'const K_VERSION = "{cpp_version(shaders_cpp)}";')
    out.append("")
    for name, symbol in SHADERS:
        out.append(f"const {name} = `{escape_template(cpp_shader(shaders_cpp, symbol))}`;")
        out.append("")

    out.append("// source/Shaders.h: the print data's layout, one row of RGBA32F texels.")
    out.extend(assignments("SHADERS_H", scalars(shaders_h, "int", "SHADERS_H")))
    out.append("")

    out.append("// source/Model.h: the film, the shutter, the weave, the print, the dyes.")
    out.extend(assignments("MODEL_H", scalars(model_h, "double|float|int", "MODEL_H")))
    out.append("")

    out.append("// source/Controls.h and Controls.cpp: the option lists, the rates, the lamps.")
    out.extend(assignments("CONTROLS_H", scalars(controls_h, "int", "CONTROLS_H")))
    for js, fn in (("FPS_NAMES", "FpsName"), ("BLADES_NAMES", "BladesName"), ("LAMP_NAMES", "LampName")):
        out.append(f"const {js} = [" + ", ".join(f"'{n}'" for n in names_of(controls_cpp, fn)) + "];")
    out.append("const FPS_RATES = [" + ", ".join(table_of(controls_cpp, "Fps", "rates")) + "];")
    out.append("const LAMP_KELVIN = [" + ", ".join(table_of(controls_cpp, "LampKelvin", "kelvin")) + "];")
    out.append("")
    out.append(END)
    return "\n".join(out)


def region(js):
    start = js.find(BEGIN)
    stop = js.find(END)
    if start < 0 or stop < 0 or stop < start:
        return None
    return start, stop + len(END)


def main():
    text = block()
    if "--print" in sys.argv:
        print(text)
        return 0
    with open(PLUGIN_JS) as handle:
        js = handle.read()
    where = region(js)
    if where is None:
        raise SystemExit("demo/plugin.js has no generated block (the BEGIN/END GENERATED lines)")
    updated = js[: where[0]] + text + js[where[1]:]
    if updated == js:
        print("demo/plugin.js already matches the plugin's sources")
        return 0
    with open(PLUGIN_JS, "w") as handle:
        handle.write(updated)
    print("demo/plugin.js: generated block rewritten from source/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
